[DeviceInfo]
deviceName=AirPods Pro
hearingAidEnabled=false
magicAccEncKey="@ByteArray(U\xb9\x91\xcc\xf0\xdd{7\xf0=C\xe\xca\x83\t\a)"
magicAccIRK=@ByteArray(\xd5\x9a\x9f#\xb2\n\xa5\x9d\x8c\x33\v\xae\v>\xd1\xa1)
model=5
